import type {
  AtlasManifest,
  AtlasSnapshot,
} from "../types";

/**
 * Loads the atlas manifest generated by the backend.
 */
export async function loadManifest(): Promise<AtlasManifest> {
  const response = await fetch("/atlas/atlas_manifest.json");

  if (!response.ok) {
    throw new Error(
      `Failed to load atlas manifest (${response.status})`
    );
  }

  return response.json();
}

/**
 * Loads a specific atlas snapshot file.
 */
export async function loadSnapshot(
  file: string
): Promise<AtlasSnapshot> {
  const response = await fetch(`/atlas/${file}`);

  if (!response.ok) {
    throw new Error(
      `Failed to load atlas snapshot ${file} (${response.status})`
    );
  }

  return response.json();
}

/**
 * Loads the newest available snapshot.
 *
 * Uses the manifest rather than assuming
 * the latest year is always 2025.
 */
export async function loadLatestSnapshot(): Promise<AtlasSnapshot> {
  const manifest = await loadManifest();

  if (manifest.states.length === 0) {
    throw new Error("Atlas manifest contains no states.");
  }

  const latest =
    manifest.states[manifest.states.length - 1];

  return loadSnapshot(latest.file);
}